# Generated by Django 4.2.4 on 2024-02-02 21:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PLEASE NAME EXPERIMENT', max_length=100)),
                ('researchers', models.ManyToManyField(related_name='experiments', to=settings.AUTH_USER_MODEL)),
                ('token_identifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_identified_experiment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 2, 2, 20, 22, 44, 820291, tzinfo=datetime.timezone.utc), help_text='Timestamp of when the data was recorded')),
                ('csvData', models.TextField(default='', help_text='CSV data from the Unity Project')),
                ('experiment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='unity_data', to='rest.experiment')),
            ],
        ),
    ]
