# Generated by Django 4.2.4 on 2024-02-02 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_unitydata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitydata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 20, 40, 17, 368074, tzinfo=datetime.timezone.utc), help_text='Timestamp of when the data was recorded'),
        ),
    ]
