# Generated by Django 4.2.4 on 2024-02-02 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_alter_unitydata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitydata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 20, 42, 11, 387553, tzinfo=datetime.timezone.utc), help_text='Timestamp of when the data was recorded'),
        ),
    ]
