# Generated by Django 4.2.4 on 2024-02-02 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_remove_experiment_token_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitydata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 21, 6, 24, 148050, tzinfo=datetime.timezone.utc), help_text='Timestamp of when the data was recorded'),
        ),
    ]
