# Generated by Django 4.2.4 on 2024-02-03 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_alter_unitydata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitydata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 21, 52, 45, 107628, tzinfo=datetime.timezone.utc), help_text='Timestamp of when the data was recorded'),
        ),
    ]
